_target_: models.airflow_module.AirflowModule

net:
  _target_: src.models.modules.airflow_models.PointNet.PointNet
  encoder: [7, 64, 64, 8]
  decoder: [8, 64, 64, 4]
  base_nb: 8

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: ${model.optimizer.lr}

is_whole: false
compile: true
