# https://mlflow.org

mlflow:
  _target_: lightning.loggers.mlflow.MLFlowLogger
  experiment_name: ${task_name}
  tracking_uri: null
  tags: null
  save_dir: ./mlruns
  prefix: ""
  artifact_location: null
