# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}"
  name: null
  version: ${task_name}
  log_graph: False
  default_hp_metric: True
  prefix: ""
