_target_: datamodules.airflow_datamodule.AirflowDataModule

data_dir: "${paths.data_dir}"
task: full
batch_size: 1
num_workers: 4
pin_memory: true
dataset:
  _target_: src.datamodules.datasets.airflow_dataset.AirflowDataset
  _partial_: true
  sample_size: 32000